pipeline {
    agent {
        docker {
            image 'nginx:latest'
            args '-p 8000:8000'
            reuseNode true
        }
    }
    triggers {
        githubPush()
    }
    stages {
        stage('location check') {
            steps {
                sh 'ls -la'
            }
        }
        stage('copy source') {
            steps {
                sh 'cp -f src/index.html /usr/share/nginx/html/'
            }
        }
        stage('curl test') {
            steps {
                sh 'curl -s localhost:8000'
            }
        }
    }
}