pipeline {
    agent any
    triggers {
        githubPush()
    }
    stages {
        stage('docker tcp connect') {
            steps {
                script {
                    docker.withServer('tcp://docker-server:2376') {
                        docker.image('nginx:latest').withRun() {
                            /* do things */
                            echo "It Works"
                        }
                    }
                }
            }
        }
        stage('test') {
            steps {
                sh 'curl localhost:8000'
            }
        }
    }
}