pipeline {
    agent {
        docker {
            image 'nginx:latest'
            args '-p 8000:8000 --name static-web'
            reuseNode true
        }
    }
    triggers {
        githubPush()
    }
    stages {
        stage('test') {
            steps {
                sh 'curl localhost:8000'
            }
        }
    }
}